kind: pipeline
type: docker
name: default
steps:
    - name: restore-cache #恢复缓存
      image: drillster/drone-volume-cache
      pull: if-not-exists
      volumes:
          - name: cache
            path: /cache
      settings:
          restore: true
          mount:
              - ./node_modules
              - .pnpm-store/v3
    - name: build
      image: node:16
      pull: if-not-exists
      commands:
          - npm i -g pnpm
          - pnpm install
          - pnpm build
          - echo 打包成功...
    - name: rebuild-cache #重建缓存
      image: drillster/drone-volume-cache
      pull: if-not-exists
      volumes:
          - name: cache
            path: /cache
      settings:
          rebuild: true
          mount:
              - ./node_modules
              - ./.pnpm-store/v3
    - name: docker
      image: plugins/docker
      pull: if-not-exists
      settings:
          repo: hurole/vue3-admin
          username:
              from_secret: docker_user
          password:
              from_secret: docker_pwd
          auto_tag: true
    - name: deploy
      image: docker:dind
      volumes:
          - name: dockersock
            path: /var/run/docker.sock
      commands:
          - docker stop vue
          - docker rm vue
          - docker run -d --name vue --restart always -p 9080:80 hurole/vue3-admin:latest
          - docker ps -a
volumes:
    - name: dockersock
      host:
          path: /var/run/docker.sock
    - name: cache
      host:
          path: /tmp/cache
trigger:
    branch:
        include:
            - main
    event:
        include:
            - cron
            - custom
