kind: pipeline
type: docker
name: vue3-admin

steps:
    - name: build
      image: node:16
      pull: if-not-exists
      commands:
          - npm i -g pnpm
          - pnpm install
          - pnpm build
          - echo 打包成功...
    - name: docker
      image: plugins/docker
      pull: if-not-exists
      settings:
          repo: hurole/vue3-admin
          username:
              from_secret: docker_user
          password:
              from_secret: docker_pwd
          auto_tag: true
          dry_run: true
trigger:
    branch:
        include:
            - main
    event:
        include:
            - cron
            - custom
